### ISSUE TITLE
Wrong Tags for Squad and Subnautica

### ISSUE THREAD

**Issue by hansdampfinger666** [CorruptComputer/ProtonDB-to-Steam-Library#22]
Not sure if I understand the code correctly, do you actually read the overall rating of the game on ProtonDB or something else?

If the former is the case, then I wanted to let you know that Squad and Subnautica are both being classified as Gold (just ran the script). Both are Silver overall on ProtonDB.

**Comment by hansdampfinger666** [comment]
Anno 1404 is Gold, not Silver.

**Comment by CorruptComputer** [comment]
This is actually due to how ProtonDB handles rankings. I chose to use `trendingTier` rather than just `tier`, as it more accurately reflects how the game is with the current state of Proton, rather than how it was with previous versions. For example with Squad API Call: https://www.protondb.com/api/v1/reports/summaries/393380.json
```
{
  "confidence": "strong",
  "score": 0.39,
  "tier": "silver",
  "total": 40,
  "trendingTier": "gold",
  "bestReportedTier": "platinum"
}
```

**Comment by hansdampfinger666** [comment]
Very interesting, thanks for clarifying and thanks for making the script!

**Comment by CorruptComputer** [comment]
Since this is a limitation with ProtonDB's API I'm going to close this.
